export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_IN_SAGA = "LOG_IN_SAGA";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SAGA = "REGISTER_SAGA";

export const ALERT_SAGA = "ALERT_SAGA";
export const ALERT_SAGA_REMOVE = "ALERT_SAGA_REMOVE";

export const BLOGPOST_SAGA = "BLOGPOST_SAGA";
export const BLOGPOST_SUCCESS = "BLOGPOST_SUCCESS";
export const BLOGPOST_FAILED = "BLOGPOST_FAILED";

export const GET_ALL_POST_SAGA = "GET_ALL_POST_SAGA";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILED = "GET_ALL_POST_FAILED";
