export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_IN_SAGA = "LOG_IN_SAGA";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SAGA = "REGISTER_SAGA";

export const ALERT_SAGA = "ALERT_SAGA";
export const ALERT_SAGA_REMOVE = "ALERT_SAGA_REMOVE";
