export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_IN_SAGA = "LOG_IN_SAGA";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SAGA = "REGISTER_SAGA";

export const ALERT_SAGA = "ALERT_SAGA";
export const ALERT_SAGA_REMOVE = "ALERT_SAGA_REMOVE";

export const BLOGPOST_SAGA = "BLOGPOST_SAGA";
export const BLOGPOST_SUCCESS = "BLOGPOST_SUCCESS";
export const BLOGPOST_FAILED = "BLOGPOST_FAILED";

export const GET_ALL_POST_SAGA = "GET_ALL_POST_SAGA";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_FAILED = "GET_ALL_POST_FAILED";

export const GET_USER_POSTS_SAGA = "GET_USER_POSTS_SAGA";
export const GET_USER_POSTS_SUCCESS = "GET_USER_POSTS_SUCCESS";
export const GET_USER_POSTS_FAILED = "GET_USER_POSTS_FAILED";

export const GET_USER_SAGA = "GET_USER_SAGA";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

export const NEW_USER_POST_SAGA = "NEW_USER_POST_SAGA";
export const NEW_USER_POST_SUCCESS = "NEW_USER_POST_SUCCESS";
export const NEW_USER_POST_FAILED = "NEW_USER_POST_FAILED";

export const POST_LINK_SAGA = "POST_LINK_SAGA";
export const POST_LINK_SUCCESS = "POST_LINK_SUCCESS";
export const POST_LINK_FAILED = "POST_LINK_FAILED";

export const EXIT_USER_POST_SAGA = "EXIT_USER_POST_SAGA";
export const EXIT_USER_POST_SUCESS = "EXIT_USER_POST_SUCESS";

export const LOG_OUT_SAGA = "LOG_OUT_SAGA";
export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS";
export const LOG_OUT_FAILED = "LOG_OUT_FAILED";

export const DELETE_POST_SAGA = "DELETE_POST_SAGA";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";

export const REFRESH_SAGA = "REFRESH_SAGA";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAILED = "REFRESH_FAILED";
